services:
  - type: web
    name: gdm-backend
    runtime: python
    rootDir: server
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 120 --workers 2
    envVars:
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
